kind2-mc/kind2

src/invGenGraph.ml

Term mining was not mining terms, and was expecting them to have an offset of zero.

Fixed invGen external interface.

---

src/CVC4Driver.ml
src/QE.ml
src/SMTExpr.ml
src/SMTExpr.mli
src/SMTLIBSolver.ml
src/SMTSolver.mli
src/Z3Driver.ml
src/flags.ml.in
src/flags.mli
src/genericSMTLIBDriver.ml
src/solverDriver.ml
src/solverDriver.mli
src/solverSig.mli
src/symbol.ml
src/symbol.mli
src/term.ml
src/term.mli
src/termLib.ml
src/termLib.mli
src/transSys.ml
src/transSys.mli
src/yicesDriver.ml
src/yicesNative.ml

Resolves kind2-mc/kind2-dev#68
Fixes kind2-mc/kind2-dev#81
A logic fragment is represented internally as a set of features (e.g. ```{UF, IA, LA}``` for ```QF_UFLIA```).
The logic is detected by going through the terms at the time of construction of the system (e.g. division by a constant is classified as a linear operation). Though the default is to not detect the logic for the moment (we need to eliminate ```div```, ```mod```, ... for Yices driver). The detection can be enabled by the flag ```--smtlogic detect```, or a specified logic can be passed to the underlying SMT solver with _e.g._ ```--smtsolver QF_LIA```.
Handling of this set of features is done in a solver specific way.
- For example, Z3 does not support ```QF_LIRA``` so it uses a larger logic ```QF_AUFLIRA``` instead.
- CVC4 …

Detect logic fragment for input system (Fixes kind2-mc/kind2-dev#68)

---

src/analysis.ml
src/analysis.mli
src/event.ml
src/kind2.ml
src/termLib.ml
src/termLib.mli

Fixes the odd parallelism issues we had so far. The problem seems to be that when sending sigterm to terminate kids, setting a timeout and waiting for the answer or the end of the timeout, sigalarm was ignored. Since the timeout throws sigalarm, it was missed by the supervisor / invariant manager causing it to hang.
This is fixed, but unfortunately does not completely work. For some reason sending sigterm to the kids does not seem to be doing anything.
So right now, the supervisor sends sigterm to the kids, sets a timeout of 0.3 seconds, and waits observing the kids. The kids do not respond to the sigterm and the supervisor timeouts, at which point it sends them sigkills and wait without a timeout. If after that some kids are still alive (maybe the user ctrl+c-ed), a warning is output to …

Parallelism fix

---

tests/lustre/contracts/PilotFlying-condacts.lus
tests/lustre/contracts/PilotFlying-no-condacts.lus

A contract at top level (R3) which was encoding two modes in its ensures.

Improved spec for pilot flying examples.

---

src/lustreLexer.mll
src/lustreParser.mly

Contract calls can be written as
```
--!contract : <contract_node_name> ;
```
It is exactly the same as
```
--@contract <contract_node_name> ;
```

Support for --! annotation for contracts.

---

src/transSys.ml

Callers would be removed when adding an extra call to an already existing node call.

Bug fix in TransSys.add_caller

---

src/lustreAst.ml
src/lustreAst.mli
src/lustreLexer.mll
src/lustreNode.ml
src/lustreParser.mly
src/lustreSimplify.ml
tests/lustre/annotations/stopwatch-multi-mains.lus
tests/lustre/annotations/stopwatch-sub.lus
tests/lustre/annotations/stopwatch-top.lus

Support for `--!<key> : <value> ;` for
* `<key>=PROPERTY` and `<value>=<expr>`.
Equivalent to `--%PROPERTY <expr> ;`
* `<key>=MAIN` and `<value>=<bool>`.
Sets the value of the `is_main` flag (`lustreNode.ml`) of the node to `<value>`.
`--%MAIN ;` is equivalent to `--!MAIN : true ;`.
This means that only the last main annotation (`!` or `%`) matters.

Bang annotations for properties and main node annotation.

---

src/lustreExpr.ml
src/lustreExpr.mli
src/lustreSimplify.ml

Accept ```pre in``` where ```in``` is a constant input, and make it equal to ```in```.
Reject node calls where a non-constant input is given to constant input parameter.

Bugfixes for constant node inputs

---

tests/lustre/contracts/PilotFlying-noCondacts.lus

The specification is stronger than in the original system. It requires that when the transfer switch is pressed, there is exactly one raise of left or right. As opposed to one or more in the original lustre specification.

Fully specified condact-free pilot flying.

---

tests/lustre/test-alias.lus

```LustreSimplify``` compared state variables with polymorphic equality. This may fail, see test case ```tests/lustre/test-alias.lus```.

Compare with equality on state variables

---

src/invGenGraph.ml
src/lockStepDriver.ml
src/step.ml
src/transSys.ml

Problem was a continuation where the step instance of the invariant generation. When splitting candidate invariants between falsifiable and valid, in the sat case the algorithm did not pop before iterating until it gets unsat.
So check-sat occuring later would end up being unsat because of un-popped asserts.

Fixed continuation making invgen with push pop unsound (closes #96)

---

src/CVC4Driver.ml
src/IC3.ml
src/MathSAT5Driver.ml
src/SMTLIBSolver.ml
src/SMTSolver.ml
src/SMTSolver.mli
src/Yices2SMT2Driver.ml
src/Z3Driver.ml
src/base.ml
src/event.ml
src/flags.ml.in
src/flags.mli
src/lib.ml
src/lib.mli
src/lockStepDriver.ml
src/solverDriver.ml
src/solverDriver.mli
src/step.ml
src/term.ml
src/term.mli
src/termAttr.ml
src/termAttr.mli
src/yicesDriver.ml
src/yicesNative.ml

Moved code out of the continuations of `check_sat_assume`, IC3 works correctly if `check-sat` with assumptions is simulated by asserting the literals on a new context level that is popped after the `check-sat`. This allows us to use CVC4 for IC3 again.
Extended the interface to `check_sat_assume` and added two convenience functions:
- The continuations now get the solver instance their first argument, so that we can factor out and re-use the functions. 
- `check_sat_ssume_tf` does not take continuations as arguments but returns `true` if the context is satisfiable with the assumptions, and `false` otherwise.
- `check_sat_assume_ab` takes two continuations of different types and returns either `Sat of 'a` or `Unsat of 'b`, where `'a` is the return type of the first continuation and `'b` …

Fix IC3 with simulated check-sat with assumptions

---

pullrequest_server/pullrequest_server.eliom
pullrequest_server/test_pr

Fixes a problem that would occur when a pull request was made to a branch that would update another already opened pull request to a different branch at the same time.
The status message for the pull request will in this case contain as many status reports as there are base branches for this pull request, like the following:
Also now if the pull request contains the string `%notest`, then nothing will be triggered on the integration server (useful for small updates outside of `src`).
For instance this pull request won't trigger any tests.

Improvements on web-hook testing

---

src/SMTLIBSolver.ml
src/event.ml
src/event.mli
src/invarManager.ml
src/kind2.ml
src/yicesNative.ml

Properties will now be shown if:
- Kind 2 was run with a single engine (in single process mode)
- if it exited due to an error

Display property statuses on exit

---

src/event.ml
src/strategy.ml

* an analysis now starts with `<AnalysisStart .../>` containing the info from the previous `<Analysis ...>`
* it ends with `<AnalysisStop/>`
* silenced a `printf` in refiner
* cleaner xml log termination in case of timeout / error
Previously analyses were wrapped in an `Analysis` tag:
```xml
<Analysis top="..." concrete="..." abstract="..." assumptions="...">
...
</Analysis>
```
The problem is that with most parsers you would not have access to the info in the Analysis tag until you see `</Analysis>`.
So for instance you would not know which system and abstraction the messages output correspond to.
This is a problem for providing real-time info to the user of tool using Kind 2.
With these new tags the parser can first parse
```xml
<AnalysisStart top="..." concrete="..." abstract="..." …
```

Easier-to-parse XML output

---

src/lustre/lustreContext.ml
src/lustre/lustreDeclarations.ml
src/lustre/lustreLexer.mll
src/lustre/lustreParser.mly
src/lustre/lustreSimplify.ml
src/lustre/lustreTransSys.ml
tests/lustre/PilotFlying.lus
tests/lustre/stopwatch-condact.lus
tests/lustre/stopwatch.lus
tests/lustre/test-condact.lus
tests/lustre/test-func.lus
tests/lustre/test-fwd-ref.lus
tests/lustre/test-issue-123.lus
tests/lustre/test-issue-127.lus
tests/lustre/test-merge.lus
tests/lustre/test-nodes.lus
tests/lustre/test-oracles.lus
tests/lustre/test-subranges.lus
tests/regression/falsifiable/stopwatch-condact.lus
tests/regression/falsifiable/stopwatch.lus
tests/regression/falsifiable/test-issue-116-2.lus.log
tests/regression/falsifiable/test-issue-123.lus
tests/regression/falsifiable/test-issue-127.lus
tests/regression/falsifiable/test-oracles.lus
tests/regression/success/block_annot_syntax.lus
tests/regression/success/test-alias.lus
tests/regression/success/test-condact.lus
tests/regression/success/test-issue-317.lus

* fixed a bug in oracle generation for unguarded pre-s
* block comment annotations for properties, main, labels and contracts
* *[edit]* prefixed `mode`, `require`, `ensure` in block contracts by `@` so that they're not reserved
Block comment annotations are for writing multi-line expressions (*e.g.* in a property or a require/ensure) while preserving compatibility with annotation-agnostic tools.
Before we would do
```
--%PROPERTY (
in > 0 => out < 0
) and (
in = 0 => out = 0
);
```
causing most other tools to fail with a parsing error.
The lexing/parsing was modified substantially for block comment annotations.
Before Kind 2 accepted the `MAIN` annotation in both
```
--%MAIN ;
--%MAIN
```
The latter is now illegal and causes a parse error.
See [here][sample file] for a full example.
With …

Block comment annotation + oracle generation fix

---

src/analysis.ml
src/analysis.mli
src/base.ml
src/event.ml
src/flags.ml.in
src/inputSystem.ml
src/invarManager.ml
src/kind2.ml
src/lustre/lustreTransSys.ml
src/step2.ml
src/strategy.ml
tests/lustre/contracts/refinement.lus

Refinement is sound: we only refine `n` if `n` was proved to verify its contract.
So when refining, look at the status of the properties of the previous analysis:
* k-true is still k-true
* invariant is still invariant
* unknown is still unknown
* 0-false is now unknown
* **k-false** for k>0 is now **(k-1)-true**
So if `P` was previously falsified at 5, after refinement we know we only need to check it from 5.
Modified base to not check properties that are k'-true when it's checking k <= k'.
If there's nothing to check at k but there's still unknown properties, base will unroll the system and move on to k+1. See example below.
Also added actlit deactivation in base.
Example [`tests/lustre/contracts/refinement.lus`][example]:
```
node count (in: bool) returns (cpt: int) ;
let
cpt = (if in …
```

Reuse previous results when refining

---

.gitignore
src/analysis.ml
src/analysis.mli
src/event.ml
src/inputSystem.ml
src/lustre/lustreNode.ml
src/lustre/lustreSlicing.ml
src/lustre/lustreTransSys.ml
src/step2.ml
src/strategy.ml
src/strategy.mli
src/subSystem.ml
src/subSystem.mli
src/testgenDF.ml
tests/lustre/contracts/refinement.lus
tests/lustre/contracts/refinement_one_mode_active.lus

* mode completeness check
* cleaned `Analysis.param` a bit
* minor fixes in step2 that were triggering harmless warnings
Relevant testcases:
* [tests/lustre/contracts/refinement.lus][test 1]
* [tests/lustre/contracts/refinement_one_mode_active.lus][test 2]
When a system has a contract (`a`,`g`,`m`) where `m = { req_i, ens_i }` is not empty, run an analysis on the abstract system
```
a /\ { req_i => ens_i }
```
with property `\/ { req_i }`.
If it succeeds analyze the concrete system as usual.
If it fails stop. We stop because since the spec is not safe, it is meaningless to abstract that node above in the hierarchy.
The general argument is that there is a problem in the spec and it should be fixed before we do anything else.
[test 1]: …

New contracts semantics

---

src/step.ml

Although unlikely, step was able to have falsified properties asserted negatively at `k+1`.
This was due to a stupid bug causing the creation of the negative activation literals to use an old list of properties to check, the version before communication happens and falsified properties are removed.
More precisely the bug is [here][step bug], it should be `unfalsifiables'` and not `unfalsifiable`.
Changed the naming so that the new version is also called `unfalsifiable` and shadows the old, obsolete one.
Big up Rémi Delmas for noticing the bug.
[step bug]: https://github.com/kind2-mc/kind2/blob/develop/src/step.ml#L542 (Line of the bug in step.ml)

Fixed stupid bug in step

---

src/SMTLIBSolver.ml
src/flags.ml
src/flags.mli
src/lustre/lustreAst.ml
src/lustre/lustreAst.mli
src/lustre/lustreContext.ml
src/lustre/lustreContext.mli
src/lustre/lustreContract.ml
src/lustre/lustreContract.mli
src/lustre/lustreDeclarations.ml
src/lustre/lustreExpr.ml
src/lustre/lustreLexer.mll
src/lustre/lustreParser.mly
src/testgenTree.ml
src/type.ml
src/type.mli
src/yicesNative.ml
tests/regression/error/check_type.lus
tests/regression/error/test-func-sliced.lus
tests/regression/falsifiable/test-oracles.lus
tests/run.sh

- More concise module (use `include Make_Spec (struct end)`)
- Default output directory for an input `file.lus` is `./file.out/`
- SMT traces are produced in `./file.out/smt_trace`
- Fix shift/reduce conflicts
- Removed inline contracts  (**Beware:** _e.g_, `--@assume ...` is now a comment and ignored)
- Allow contracts items in any order
- Guarantees / assumptions / ensures ... can now be named, _e.g._, `guarantee "my guarantee" x > 1;`
Revert to typing integer constants like `1` as `[1;1]`, but now the type is generalized when we want to introduce abstractions as state variables.

Improvements in parsing and flags

---

src/kind2.ml
src/lustre/lustreContext.ml
src/lustre/lustreContext.mli
src/lustre/lustreDeclarations.ml
src/lustre/lustreNode.ml
src/lustre/lustreNode.mli
src/lustre/lustreSimplify.ml
tests/regression/error/cocospec_node_call_check.lus

Discovered by John Backes (thanks!)
Mentioning the outputs of the node in the assumptions / requirements of the contract of a node is illegal. Inputs of node calls where not checked, it was thus easy to bypass the check by calling, say, a pass-through node.
See regression test added in this PR for more details.

Bugfix no outputs in assumptions/requires check

---

src/flags.ml
src/flags.mli
src/inputSystem.ml
src/inputSystem.mli
src/kind2.ml
src/lustre/contractsToProps.ml
src/lustre/contractsToProps.mli
src/lustre/lustreAst.ml
src/lustre/lustreAst.mli
src/lustre/lustreInput.ml
src/lustre/lustreInput.mli
src/lustre/lustreNode.ml

Translation of Kind 2 contracts in terms of assertions and properties
Limitations (justified below):
- does not generate properties corresponding to calls being safe
- untyped ghost variables are unsupported
- contract node declarations and contract imports are not supported
These limitations come from the primary goal of the translator, which is to stay as close as possible to the original file. That is, no intermediary variables, no oracles for unguarded `pre`'s...
To achieve this, the translator works on the AST before all the contextual checks (typing, contract sanity checking, *etc.*). Still, we will not compile a system that does not pass these checks: Kind 2 will parse and construct the input system as usual before it retrieves the AST and translates the contracts.

Contracts to props

---

src/lustre/lustreDeclarations.ml
src/lustre/lustreParser.mly
tests/regression/success/block_annot_syntax.lus
tests/regression/success/contract_ordering.lus
tests/regression/success/mode_reqs_by_idents.lus
tests/regression/success/mode_reqs_by_idents_shadowing.lus

Ghost variables were actually treated as constants. That is, they could not mention `pre` of themselves. This is fixed now.
**NB:** the type annotation for ghost variables is **no longer optional**. The syntax is
```
var blah: bool = ... ;
```
The type annotation for constants however is still optional.

Contract var stream fix

---

src/flags.ml
src/flags.mli
src/lustre/lustreContext.ml
src/lustre/lustreContract.ml
src/lustre/lustreLexer.mll
src/lustre/lustreToRust.ml

Original lustre files are now included in the docs and can be (line-)referenced from the docs.
- also rmed spurious print statement from previous PR
- fixed contract item ordering (most were reversed, ok internally but weird in result of compilation)

To rust docs improvements

---

src/transSys.ml

Fixes a bug when two property have the same name, *i.e.* either the same expression or the same user-specified name.
In that case, assuming it proved both, Kind 2 would say it manages to prove one but never terminate.

Fix to set_status in TransSys

---

src/lustre/lustreDeclarations.ml
src/lustre/lustreNode.mli
tests/regression/error/unguarded_pre_in_contract.lus
tests/regression/error/unguarded_pre_in_contract_call.lus
tests/regression/error/unguarded_pre_node_call_in_contract.lus
tests/regression/falsifiable/test-oracles.lus

Bans unguarded pre-s from
- contract items: assumes, guarantees, requires, ensures
- contract imports: in/out params
- node called in contracts
So, unguarded pre-s are completely banned from the cone of influence of the contracts.

Fixes regarding unguarded pre-s in contracts

---

src/analysis.ml
src/analysis.mli
src/certifChecker.ml
src/event.ml
src/event.mli
src/flags.ml
src/flags.mli
src/invarManager.ml
src/jkindParser.ml
src/kind2.ml
src/lib.ml
src/lib.mli
src/lustre/lustreContext.ml
src/lustre/lustreDeclarations.ml
src/lustre/lustreExpr.ml
src/lustre/lustreIdent.ml
src/lustre/lustreIdent.mli
src/lustre/lustreTransSys.ml
src/nativeInput.ml
src/stat.ml
src/stat.mli
src/stateVar.ml
src/stateVar.mli
src/strategy.ml
src/transSys.mli

- `--compile` forces `--lus_strict`: no unguarded pre's when compiling (also updated [TCM repo](https://github.com/kind2-mc/cocospec_tcm_experiments))
- added global flag to completely disable refinement
- factored reserved ids in `Lib`
- feedback improvements:
- total vs analysis time: analysis time is now used everywhere except in the final breakdown
- added the time of the analysis in `Analysis.result`
- when printing the abstraction map, slice it to the current system (*i.e.* don't report the status of the systems **above** the current system)
- report refined node in final breakdown
- other minor improvements to feedback (mostly in the final breakdown)

Refinement flag, rust compile fix, feedback improvements

---

src/certif/certifChecker.ml
src/certif/jkindParser.ml
src/certif/proof.ml
src/certif/proof.mli
src/event.ml
src/flags.ml
src/flags.mli

Trust statements are exported with a proof to be added manually, in an additional auxiliary LFSC file. This is activated with option `--log_trusted true`.
Don't show step first state of step counter examples to not confuse users.

Log trusted assumptions in proofs as additional goals and better step counterexamples

---

src/lustre/lustreDependencies.ml

Otherwise Kind 2 loop on things like:
```
type t0 = t1;
type t1 = t2;
type t2 = t0;
```

Transitivity in dependency analysis of forward references

---

lfsc/signatures/kind.plf
src/certif/certifChecker.ml

Perform under approximation as a first phase (identify invariants that **have** to be in any _k_-inductive strengthening of the property).
Disabled for now by default because it is useless.

Under approximation for minimization of certificates (disabled)

---

doc/usr/content/2_input/1_lustre.md
src/lustre/lustreDeclarations.ml
src/lustre/lustreExpr.ml
src/lustre/lustreSimplify.ml
tests/regression/error/const_not_const.lus
tests/regression/error/empty_range.lus

Do not allow non constant expression in constant stream definitions. The following is now illegal:
```Lustre
const a : int = 1 -> 0;
```
Forbid empty sub-range types. The following declarations are now illegal:
```Lustre
type empty = subrange [1, 0] of int;
const a : subrange [1, 0] of int;
node n (x: subrange [-8, -100] of int) returns ...
```

Additional restrictions on constants and sub-ranges in Lustre

---

doc/usr/content/2_input/1_lustre.md
src/inputSystem.ml
src/lustre/contractsToProps.ml
src/lustre/lustreAst.ml
src/lustre/lustreAst.mli
src/lustre/lustreContext.ml
src/lustre/lustreContext.mli
src/lustre/lustreDeclarations.ml
src/lustre/lustreDependencies.ml
src/lustre/lustreLexer.mll
src/lustre/lustreNode.ml
src/lustre/lustreNode.mli
src/lustre/lustreParser.mly
src/lustre/lustreSlicing.ml
src/strategy.ml
src/strategy.mli
src/subSystem.ml
src/subSystem.mli
tests/regression/error/extern_fun_no_body.lus
tests/regression/error/extern_node_no_body.lus
tests/regression/success/extern.lus

- `extern` keyword
- docs:
- partially undefined nodes
- extern + extern VS partially undefined nodes
- functions + benefits (more precise abstraction)
- reg tests for `extern`
External nodes and functions are just like any other except for a flag. This flag is used during the strategy pass and forces to abstract them by their (potentially empty) contract.

Extern nodes and functions

---

src/lustre/lustreExpr.ml
src/terms/numeral.mli

Typing now propagates int ranges through operator application, hence improving our *static analysis* for subranges correctness.

Improved subrange treatment for operator

---

examples/syntax-test.lus
src/lustre/lustreLexer.mll
src/terms/decimal.ml
src/terms/hexadecimal.ml
src/terms/hexadecimal.mli
src/terms/numeral.ml
tests/regression/success/test-hex.lus

Hello,
I'm experimenting Kind-2 for proving numerical properties of Lustre programs extracted from C code.
This is how I discovered the missing simplifications of #504.
Writing large or precise numerical constants can be an issue. However, according to Lustre v6 specification §2.2 : 
> _Floating_ and _Integer_ stands for decimal floating point and integer notations, following C standard
Hence, I suggest this pull request thats allows users of Kind-2 to use C hexadecimal notations for both numerals and decimals constants.
Examples have been added to `examples/syntax-test.lus` and basic unit tests in `tests/regression/success/test-hex.lus`.
Any comment welcome,
Best regards.

Hexadecimal notations for numerical constants

---

src/flags.ml
src/flags.mli
src/model.ml
src/terms/decimal.ml
src/terms/decimal.mli
src/terms/numeral.ml

When Kind-2 outputs counter examples, decimal values are represented by rationals which are, in my opinion,  cumbersome to read. By the way, those rationals are messy Lustre values, since _eg._ `1/8` is actually the _integer_ `0` and not the expected _real_ `0.125` value.
Indeed, the code documentation (which is quite excellent, I must say) for printing model values contains this note (file `model.ml`, line 71):
> `(* TODO do we not want legal lustre values? *)`
Hence, I experimented printing an approximation of rationals in models, plus an upper bound of the « rounding » error. For instance, instead of reading decimal `1215678/251162565001`,
you would read now `+4.8402e-06+f22`, which means: approximate value `+4.8402e-06` with a (positive) _relative_ error less than `2^-22` (which fits …

Provide decimal approximations in models

---

src/utils/lib.ml

Localisation of errors in Kind-2 are not automatically detected by Emacs.

Emacs-compatible localisation of errors

---

src/lustre/lustreTransSys.ml

This prevents Kind 2 from using auxiliary variable encoding sofar which may disappear after slicing or other simplification techniques

SoFar of empty assumptions is simplified

---

.travis-ci.sh
Dockerfile
README.rst
doc/usr/source/9_other/8_interpreter.md
doc/usr/source/9_other/8_interpreter.rst
doc/usr/source/home.rst
doc/usr/source/index.rst
src/Makefile.in
src/inputParser.ml
src/inputParser.mli
src/interpreter.ml

Add support for JSON inputs for the interpreter.
Arrays, tuples and records are supported.
A page about the interpreter has been added to the documentation.

Interpreter

---

src/lustre/lustrePath.ml

Hi Daniel,
We came across a tiny bug in the JSON printing of interpreter output. When a stream has a clock, the undefined values were being filtered out just before they were printed. However, the comma between elements was still being printed - so you'd end up with multiple commas in a row like `value,,,,,`.
I fixed this by filtering out the undefined values earlier; I also removed the "show" flag from `pp_print_stream_value_json` since it was not used any more.
If you'd like a concrete test case, a simple automaton can trigger it:
```
node Ping (in : bool) returns (ping: bool)
let
automaton 
state S1
let
ping = true;
tel
until if in resume S2;
initial state S2
let
ping = false;
tel
until if in resume S1;
tel
```
Running that in the interpreter with JSON output gave a result containing …

Fix JSON printing of execution path values

---

src/inputParser.ml
src/lustre/lustreAst.ml
src/lustre/lustreAst.mli
src/lustre/lustreContext.ml
src/lustre/lustreDeclarations.ml
src/lustre/lustreIndex.ml
src/lustre/lustreIndex.mli
src/lustre/lustreSimplify.ml
tests/regression/error/abstract_type.lus
tests/regression/falsifiable/abstract_type.lus
tests/regression/success/abstract_type.lus

Hi,
This PR adds support for abstract or free types, written as types with no right-hand side equation. These abstract types can be given a semantics by defining operations on them as imported functions or nodes with no definitions, and giving these operations a contract.
I chose to represent abstract types as roughly equivalent to a struct with one
integer field. The integer describes a unique reference to an object of the
abstract type -- like a pointer. This field is implemented as a
different index type to regular record fields to ensure type safety.
In implementing this new index type, I have erred on the side of emulating
regular struct behaviour.
I chose this struct-like representation over the Abstr type in terms/types.ml
because it gives counterexamples, while Abstr did not when …

Add support for abstract/free types

---

src/invgen/invGen.ml

It was closing unproperly in case of a SMT exception (without killing SMT instances)

Uncomment exception handling in invGen

---

src/lustre/lustreDeclarations.ml
src/lustre/lustreSimplify.ml
src/lustre/lustreSimplify.mli
tests/regression/success/array-const.lus

Hi Daniel,
There was a bug where a top-level constant declaration like
```
const simple_array_literal : int^3 = [1, 5, 9];
```
was treated as a type error. This was happening because the type checking
for constants expected the trie of the type to be the same shape as
the trie of the values. However, for arrays, the values had a shape like
`[0]: _, [1]: _, [2]: _`
but the array in the type trie hadn't been flattened out, so it had
no nesting. I've fixed this for now by flattening out the array in the
type trie, so in this example, the original type:
```
Array Int (IntRange 0 3)
```
becomes the trie:
```
[0]: Int, [1]: Int, [2]: Int
```
and then we can more easily match each element of the value trie against its corresponding entry in the type trie.
I couldn't find an obviously nicer way …

Allow arrays in top-level constant declarations

---

src/kind2.ml
src/lustre/lustreContext.ml
src/lustre/lustreInput.ml
src/lustre/lustreLexer.mll

```
$ ./bin/kind2 --only_parse true -- tests/lustre/syntax-errors/array-syntax.lus
kind2 3646f46-dirty
tests/lustre/syntax-errors/array-syntax.lus:4:5: Failure cause: Unrecognized token % (0x25)
```
```
$ ./bin/kind2 -json --only_parse true -- tests/lustre/syntax-errors/array-syntax.lus
[
{
"objectType" : "log",
"level" : "info",
"source" : "parse",
"value" : "kind2 3646f46-dirty"
}
,
{
"objectType" : "kind2Options",
"enabled" :
[
"bmc",
"ind",
"ind2",
"ic3",
"invgents",
"invgenos",
"invgenintos",
"invgenintos"
],
"timeout" : 0.000000,
"bmcMax" : 0,
"compositional" : false,
"modular" : false
}
,
{
"objectType" : "log",
"level" : "error",
"source" : "parse",
"file" : "tests/lustre/syntax-errors/array-syntax.lus",
"line" : 4,
"column" : 5,
"value" : "Unrecognized token % (0x25)"
}
]
```
Xml …

Filename displayed in error messages

---

src/lustre/lustreInput.ml
src/utils/lib.ml
src/utils/lib.mli
tests/lustre/StopWatchSpec.lus
tests/lustre/contract_stopwatch_spec.lus

Error messages display style
============================
- TEXT
```
$ bin/kind2 -- tests/lustre/StopWatchSpec.lus
kind2 d991734
================================================================================================================================================================================================================================================================================
Analyzing stopwatch
with ContractCheck top: 'stopwatch'
subsystems
| concrete: ToInt, Stable, Since, Increased, Even, Count
<Success> Property stopwatchSpec._one_mode_active is valid by property directed reachability after 0.186s.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Reverting changes for adding file name/filepath into lexing buffer

---

src/flags.ml
src/flags.mli
src/ic3/IC3.ml
src/induction/compress.ml
src/induction/step.ml
src/lustre/lustreExpr.ml
src/smt/BoolectorDriver.ml
src/smt/SMTSolver.ml
src/terms/term.ml
src/terms/term.mli
src/terms/termLib.ml

This PR adds support for Boolector (an SMT solver) for Lustre problems with only machine integers. Since Boolector does not support IA/RA, an error is printed when those sub-logics are detected and Boolector is selected as the backend engine. Techniques using IA/RA are either disabled or modified to work with BV too. Finally, QF_UF logic is expanded to QF_UFBV as the former is not supported by Boolector.

Add support for Boolector as a backend engine for Kind2.

---

src/kind2.ml

This PR ensures that the logs terminate (e.g., a closing bracket is added in `-json` mode) before kind2 terminates if `--only_parse true` option is passed.

Don't forget to terminate the log if only_parse option is passed.

---

src/lustre/lustreContext.ml
src/lustre/lustreContext.mli
src/lustre/lustreDeclarations.ml
src/lustre/lustreInput.ml
src/lustre/lustreParser.mly
src/lustre/lustreReporting.ml
src/lustre/lustreReporting.mli
src/lustre/lustreSimplify.ml
src/lustre/lustreSlicing.ml

`fail_at_position` etc functions get their own module.
We would like to use them in other places and need not pull `LustreContext` as a dependency

Move reporting functions into their own module

---

examples/syntax-test.lus
src/lustre/lustreTypeChecker.ml
src/lustre/typeCheckerContext.ml
src/lustre/typeCheckerContext.mli
tests/lustre/typechecking/shouldFail/test_array_group.lus
tests/lustre/typechecking/shouldFail/test_shadowing.lus
tests/lustre/typechecking/shouldPass/test_array_group.lus
tests/lustre/typechecking/shouldPass/test_node_decl4.lus
tests/lustre/typechecking/shouldPass/test_node_decl5.lus

- Do not allow shadowing.
- Improve interface for typechecker context for contract context exports
- Separate out node and identifier contexts

Disallow shadowing and  separate namespaces for nodes and variables

---

src/lustre/lustreAstDependencies.ml
tests/lustre/typechecking/shouldFail/test_output_in_assume2.lus

There was a missing peace in the previous PR. It is fixed here. 
For reachability we should be flattening node calls using the node summary for the equations in contract guarantees and
mode requires.

flatten node calls while finding reachable vars for contract guarantees

---

src/certif/certifChecker.ml
src/certif/jkindParser.ml
src/induction/compress.ml
src/lustre/lustreSlicing.ml
src/lustre/lustreSlicing.mli
src/lustre/lustreTransSys.ml
src/nativeInput.ml
src/transSys.ml
src/transSys.mli
tests/regression/falsifiable/test-issue-715.lus

The current solution only distinguishes between constrained and unconstrained inputs.
ToDo: Refine set of constrained inputs to consider only inputs _temporally_ constrained.
This should be enough to ensure existence of equal successors in path compression.
See issue #715 for more information.

Fix soundness issue in path compression when inputs are temporally constrained

---

src/lustre/lustreAst.ml
src/lustre/lustreExpr.ml

This reverts a change introduced in commit 61fee4a. Some Kind 2 features, like printing the result of miniziming the source of a Lustre program according to a computed IVC, relies on printing types following the Lustre syntax.

Print enum types following Lustre syntax

---

src/lustre/lustreContext.ml
src/lustre/lustreExpr.ml
src/lustre/lustreExpr.mli
src/lustre/lustreSimplify.ml
tests/regression/success/array-literal-arrow.lus
tests/regression/success/array-pre-indexing.lus

Hi Daniel,
I'm looking into some bugs in the array support at the moment. I have some fixes for two small bugs. I'm looking into another one now, which is that you can't call nodes or functions inside an array definition like `x[i] = f(y[i])`. This one seems a bit hairier though.
Creating a new state var for an array select would reuse the existing
definition, but with the array indices from the environment rather
than what the select expression used.
The nested select in the following equation:
```
prevs2[i] = if i = 0 then ins else (0.0 -> pre (prevs2[i - 1]));
```
was translated as `prevs2[i]`, somehow losing the `i-1`.
Array constructors (of the form `x^n`) were causing type errors in
arrows.
For a definition like:
```
const_zero = 0.0^5 -> pre const_zero;
```
This was being …

Two small array bugs

---

src/lustre/lustreContext.ml
src/lustre/lustreContractGen.ml
src/lustre/lustreDeclarations.ml
src/lustre/lustreNode.ml
src/lustre/lustreNode.mli
src/lustre/lustrePath.ml
src/lustre/lustreSlicing.ml

Note: svar aliasing tracing was associating variables with different origin (e.g. input <-> output) and different types (int <-> subrange). This could lead to errors, so I commented it out.

Print values of ghost variables in counterexamples

---

src/kind2Flow.ml
src/lustre/lustreTransSys.ml
src/transSys.ml
src/transSys.mli

* Candidate properties instantiated in parent nodes remain candidate properties.
* No verification is done if all properties are candidate.

Fix a couple of issues with candidate properties

---

src/lustre/lustreAstHelpers.ml
src/lustre/lustreAstHelpers.mli
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreAstNormalizer.mli
src/lustre/lustreInput.ml

What the normalizer is suppose to accomplish is commented at the top of the interface file.
At the moment, the actual pass in `lustreInput` is commented out because the normalizer modifies the AST in such a way that if the code that compiles the AST to a `lustreNode` does not incorporate the `generated_identifiers` information it wont work.

Add a Lustre AST Normalizer pass

---

src/lustre/lustreAstHelpers.ml
src/lustre/lustreAstHelpers.mli
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreAstNormalizer.mli
src/lustre/lustreContext.ml
src/lustre/lustreExpr.ml
src/lustre/lustreExpr.mli
src/lustre/lustreInput.ml
src/lustre/lustreNode.ml
src/lustre/lustreNodeGen.ml
src/lustre/lustreNodeGen.mli
src/lustre/lustreSimplify.ml
src/lustre/lustreTypeChecker.ml
src/lustre/lustreTypeChecker.mli
src/terms/stateVar.ml
src/terms/stateVar.mli
src/utils/Res.mli
src/utils/lib.ml
src/utils/lib.mli

This node generation pass does not include structured data or Daniel's new properties generated for subranges or contracts. The structured data code is already written but I wasn't able to test it yet and having a smaller surface to review seemed like a good idea anyway.
Normalization needed to change slightly to record the node where the ids where generated. It may make sense to annotate the generated ids with additional information (such as whether it should be constant).
~~One thing I am unsure about: Node Calls in the old code will abstract new state variables for outputs and oracles and create equations to the effect of `abs_0 = o1` (where `abs_0` is the new abstraction and `o1` is the old state variable for the node output). It is not clear to me why this is the case or needed and …

First pass for new node generation

---

src/lustre/lustreAstNormalizer.ml
src/lustre/lustreAstNormalizer.mli
src/lustre/lustreInput.ml

This adds warnings (or errors if the strict flag is set) for unguarded pres.
This does not include unguarded pres in contracts yet, but it sets up the pipeline for adding them. When contracts are added in a future PR the requisite warnings will be added also at that time.

Add warnings/errors for unguarded pre

---

src/terms/term.ml

It is assumed in the ivcMcs module. Fix corner case.

Term module accepts empty sum and empty product

---

src/ivcMcs.ml
src/terms/term.ml

Revert commit 1465083 too: `mk_plus` and `mk_times` are polymorphic constructors.

Fix issue in ivcMcs module

---

src/ivcMcs.ml
src/modelElement.ml
src/modelElement.mli

Given enumeration type `t = enum { A=0, B=1, C=2 `}, and equation `x = A -> if y then t1 else t2`, Kind 2 currently generates constraint `0 <= V(A) <=2` for init, and constraint `0 <= (ite y t1 t2) <= 2` for trans, where `t1` and `t2` are integer variables at the SMT level. However, it discards the first constraint since it is trivially satisfied. This causes a mismatch between the number of init and trans elements. This PR accommodates situations like above.

Mismatches between init and trans elements do not fail

---

src/lustre/lustreLexer.mll

We already have to compute this path in the lexer in order to open the file, so just return it.

Switch to full relative path in the fname field for the position record

---

src/lustre/lustreAstDependencies.ml
src/lustre/lustreAstHelpers.ml
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreNodeGen.ml
src/lustre/lustreTypeChecker.ml
src/lustre/typeCheckerContext.ml

A couple of bugs were caught along the way while doing this.
The `src/invgen/invGenMiner.ml` is the last file that has the file-wide disable of warning 27. I wasn't able to confidently edit that file to remove the unused variables. Most of the instances look like just required variables in order to satisfy the functor signature, but there is one instance that looks like a bug: `octagon_3 terms terms`.

Remove warning 27 from various files

---

src/lustre/lspInfo.ml

This PR fixes a bug where an extra comma is printed for a top a declaration if the program is passed to `stdin` (i.e., `fname = ""`).

Fix LSP JSON output bug.

---

src/lustre/lustreAstDependencies.ml
tests/experimental/success/test_node_dep_with_pre_and_nested_call.lus

Because of the way `pre` expressions and expressions inside nested node calls work (with respect to sorting nodes and sorting equations) the assumption that you will always have inputs and outputs matching up is not true.

Fix assumption about matching input/output lengths in dependency analysis

---

src/ivcMcs.ml
src/lustre/contractsToProps.ml
src/lustre/lspInfo.ml
src/lustre/lustreAst.ml
src/lustre/lustreAst.mli
src/lustre/lustreAstDependencies.ml
src/lustre/lustreAstHelpers.ml
src/lustre/lustreAstHelpers.mli
src/lustre/lustreAstInlineConstants.ml
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreAstNormalizer.mli
src/lustre/lustreContext.mli
src/lustre/lustreDeclarations.ml
src/lustre/lustreDependencies.ml
src/lustre/lustreIdent.ml
src/lustre/lustreIndex.ml
src/lustre/lustreInput.ml
src/lustre/lustreLexer.mll
src/lustre/lustreNodeGen.ml
src/lustre/lustreParser.mly
src/lustre/lustreSimplify.ml
src/lustre/lustreSyntaxChecks.ml
src/lustre/lustreTypeChecker.ml
src/lustre/typeCheckerContext.ml
src/utils/hString.ml
src/utils/hString.mli
src/utils/hashconsStrong.ml
src/utils/hashconsWeak.ml
tests/ounit/lustre/testAstDependencies.ml
tests/ounit/utils/testGraph.ml

The bad news:
This change only shaves off about 2 seconds, leaving the old front-end at 0.02s and the new front-end at ~2s for the `cruise_controller` example
The good news:
After some experimentation and profiling, I decided to try commenting out the dependency sorting passes (there are only two). If no dependency sorting is done at all, the new front-end is **as fast as the old front end** (for parsing). This means that all of the remaining slow down is in the dependency sorting code.
Also, there are places in the code base where `Stdlib.compare` is used that have nothing to do with either front-end. I did not change these, should they be changed?

Improve performance by switching to HStrings immediately (at parsing time)

---

src/lustre/lustreAstDependencies.ml
src/utils/graph.ml
src/utils/graph.mli
tests/ounit/utils/testGraph.ml

After thinking about this for entirely too long. I realized that what I would have done would have ended up being a dynamic programming approach to what should already be possible with the graph setup. Thus, I decided to just try memoizing the output of the `reachable` function. And it works great. I diffed the output of the original `reachable` and the `memoized_reachable` for the `cruise_controller` example and they are identical (as one would hope!)
With this change the new front-end takes ~.04s to parse the `cruise_controller` example on my machine. 
The final incarnation memoizes with a supplied memo table (as opposed to including the table inside the `reachable` function and only having recursive calls memoized). Surprisingly this didn't turn out to be a huge win (about ~.30 …

Memoize graph reachability

---

src/lustre/lustreAstHelpers.ml
src/lustre/lustreAstHelpers.mli
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreAstNormalizer.mli
src/lustre/lustreContract.ml
src/lustre/lustreContract.mli
src/lustre/lustreNodeGen.ml
tests/experimental/success/contract_import_indirection.lus

- Fixed a bug where mode paths were computed incorrectly in a special case with contract node import indirection
- Fixed a bug where contract node outputs weren't substituted for their arguments
- Changed ordering of Lustre intermediate representation to more closely match the old frontend
- Fixed a bug with abstraction variable caches not respecting the invariants needed to be a `Map` key, put them inside a `Hashtbl` instead.
- Fixed scope of mode ensures/requires

Fix misc bugs

---

src/lustre/lustreAstDependencies.ml
src/lustre/lustreAstDependencies.mli
src/lustre/lustreNodeGen.ml
tests/ounit/lustre/testLustreFrontend.ml

- Contracts that only contained modes were getting ignored
- Added check for files with no nodes
- Fixed bug with contract ghost variables whose names contained underscores

Fix a couple more bugs

---

doc/usr/source/2_input/1_lustre.rst
doc/usr/source/9_other/1_post_analyses.rst

After skimming through the docs this was the only thing I found that needed changing

Fix doc description of top/main nodes

---

src/kind2Flow.ml
src/lustre/contractChecker.ml
src/realizability.ml
src/realizability.mli

It also provides an alternative method for the computation of the next state to the deadlocking state. The new implementation uses MaxSMT to maximize the number of guarantees satisfied by the computed state. Kind 2 uses the new method by default when Z3 is the main solver.

Make conflicts independent from last trace input values

---

src/flags.ml
src/flags.mli
src/kind2Flow.ml
src/lustre/contractChecker.ml
src/realizability.ml
src/realizability.mli

Partially revert changes of PR #852: conflicts _dependent_ on last trace input values again. It also adds a flag to disable computation of a deadlock when a contract is proven unrealizable and a flag to disable contract satisfiability check.

Update computation of deadlocking trace and conflict

---

src/lustre/lustreAstNormalizer.ml
src/lustre/lustreTypeChecker.ml
src/lustre/typeCheckerContext.ml
tests/regression/success/infer_tight_subrange.lus

Expanding type synonyms in structured types was not correctly
recursing in strucutred types when reaching a type synonym.
Comparing to original types was not fine-grained enough

fix subranges with type syns and orig types

---

src/lustre/lustreAstInlineConstants.ml
src/lustre/lustreAstNormalizer.ml
tests/regression/success/const_in_contract.lus

Fixes #878, also adds constant inlining for node/fn contracts, I assume this was accidentally missed?

Fix consts in contract

---

src/flags.ml
src/flags.mli
src/terms/ufSymbol.ml
src/utils/hashcons.ml
src/utils/hashconsWeak.ml

We found a hard-to-reproduce issue where a term that is still alive disappears from the hash-consing table that uses normal pointers (`hashconsStrong`), which should never happen! Since the problem has not been reproduced so far when the hash-consing table with weak pointers is used instead (`hashconsWeak`), this PR switches to the implementation that uses weak pointers.

Use only weak hash-consing implementation

---

doc/usr/source/1_techniques/3_invgen.rst
src/flags.ml
src/invgen/invGen.ml
src/invgen/lockStepDriver.ml
src/invgen/lockStepDriver.mli

In commit https://github.com/kind2-mc/kind2/commit/6954967d3e550e1e3e223088d78cc6b9de4c0008 non-trivial invariants are processed individually so that they are taken into account to prune next candidates. However, commit https://github.com/kind2-mc/kind2/commit/79fea6412802c2e1e2df2ca3c95097f5c650b2b9 stopped adding discovered invariants to pruner so that no information is learnt and each non-trivial invariant is discovered multiple times. Adding a call to `pruning_add_invariants` like in the [original code](https://github.com/kind2-mc/kind2/commit/6954967d3e550e1e3e223088d78cc6b9de4c0008#diff-1d69aae45111266ee95fae8a104bb4a79e61422f881ecade0dd6bcd870f0e2b2R645) would restore the intended behavior, but it has some downsides:
- Non-trivial invariants are added to the pruner twice: during …

Fixes in invariant pruning

---

src/lustre/lustreAstInlineConstants.ml
src/lustre/lustreAstNormalizer.ml
tests/regression/falsifiable/forall-pre-array.lus

They were introduced under the assumption that pre pushing was always performed.
Currently pre pushing is optional (--lus_push_pre).

Revert a few changes applied in PR #890

---

src/smt/CVC5Driver.ml

Remove `--decision=internal` (it is already the default value)
Remove `--dag-thresh=0` (added for proofs, but not required anymore)
Add `--mbqi` (good for disproving invalid properties with quantifiers)
Add `--full-saturate-quant` (avoid unknown answers)
Keep `--ext-rew-prep=agg` (helps to solve more benchmarks, in general)

Tweak cvc5 options

---

src/lustre/lustreInput.ml
src/lustre/lustreSlicing.ml
tests/ounit/lustre/testLustreFrontend.ml
tests/regression/success/array-index-check.lus

The old dependency check fails on model with arrays (see included regression test). This PR performs old dependency check only when `old_frontend` is true.

Enable new array dependency check

---

src/lustre/lustreAstDependencies.ml
src/lustre/lustreTypeChecker.ml
tests/ounit/lustre/lustreAstDependencies/contract_output_redeclaration.lus
tests/ounit/lustre/lustreAstDependencies/node_input_redeclaration.lus
tests/ounit/lustre/testLustreFrontend.ml

This PR adds the check to the new front-end. The old front-end was already doing the right thing.

Reject input/output redeclarations in nodes and contracts

---

src/certif/proof.ml

Issue introduced in commit dfc1a99

Fix printing of bitvector sort in LFSC proofs

---

src/lustre/lustreAstNormalizer.ml
src/lustre/lustreInput.ml
src/lustre/lustreNode.ml
src/lustre/lustreNodeGen.ml
src/terms/stateVar.ml

If a model includes an unnamed property that consists of just a call to a node that returns a bool, Kind 2 uses the call output as the associated state variable. Before this change, the internal name was leaked in the property id. For an example, see the analysis output for: `tests/regression/success/const_in_contract.lus`. The issue started to show up after commit c6add74.
This PR also handles a case of expression abstraction missed in c6add74

Fix leaking of internal name in property id

---

src/lustre/lustreAstNormalizer.ml

It was already doing this before, but it was changed in PR #879 (4f38d8d) to fix issue #878 (see `tests/regression/success/const_in_contract.lus`) The change does not seem necessary anymore.

Do not abstract expression if it is just a constant symbol

---

src/ic3/IC3.ml
src/smt/genericSMTLIBDriver.ml
src/terms/bitvector.mli

MathSAT `(get-value)` command returns bit-vector constants of the form `(_ bvX n)`. Kind 2 was ignoring constants in this format leading to an assertion failure. For instance, an assertion failure was triggered when running Kind 2 with `--smt_solver MathSAT --enable IC3` on [rtp_vt.lus](https://github.com/kind2-mc/kind2-benchmarks/blob/master/FMCAD08/Int32/protocol/rtp_vt.lus). This PR adds support for bit-vector constants of the form `(_ bvX n)`.
In addition, this PR makes Kind 2 replace non-standard symbols `bvudiv_i`, `bvsdiv_i`, `bvurem_i`, and `bvsrem_i` returned by some commands of z3 with SMTLIB standard symbols. See this [issue](https://github.com/Z3Prover/z3/issues/1133) for more details.

Add support for bit-vector SMT extensions 

---

src/c2i/C2I.ml
src/c2i/C2Icnf.ml
src/certif/certifChecker.ml
src/dead_code/lustreChecker.ml
src/dead_code/testgen/testgen.ml
src/ic3/IC3.ml
src/induction/base.ml
src/induction/step.ml
src/induction/step2.ml
src/interpreter.ml
src/invgen/lockStepDriver.ml
src/ivcMcs.ml
src/qe/QE.ml
src/realizability.ml
src/smt/BoolectorDriver.ml
src/smt/CVC5Driver.ml
src/smt/MathSATDriver.ml
src/smt/SMTLIBSolver.ml
src/smt/SMTSolver.ml
src/smt/SMTSolver.mli
src/smt/Yices2SMT2Driver.ml
src/smt/Z3Driver.ml
src/smt/solverSig.mli
src/smt/yicesDriver.ml
src/smt/yicesNative.ml
src/testgen/testgenSolver.ml

It also removes deprecated and unused SMT option (`:interactive-mode`)

Rename misleading SMT option parameter

---

src/certif/certifChecker.ml
src/induction/compress.ml
src/induction/compress.mli
src/induction/step.ml

It also tweaks encoding so that bit-vectors are only introduced in Boolean/Array problems when Boolector is used.

Fix path compression BV encoding in minimize_invariants

---

CHANGES.md
README.rst
doc/usr/source/home.rst
src/doc/index.mld
src/flags.ml
src/flags.mli
src/induction/compress.ml
src/smt/BitwuzlaDriver.ml
src/smt/SMTSolver.ml

In our experiments, Bitwuzla outperforms Boolector. Moreover, Bitwuzla has support for unsat cores which will be handy in the near future.

Replace Boolector with Bitwuzla

---

src/lustre/generatedIdentifiers.ml
src/lustre/generatedIdentifiers.mli
src/lustre/lustreAbstractInterpretation.ml
src/lustre/lustreAbstractInterpretation.mli
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreInput.ml
src/lustre/lustreNodeGen.ml
src/lustre/lustreRemoveMultAssign.ml

Use generated identifiers for desugaring multiple assignment, rather than modifying the input AST. Prevents internal (generated) variables from being leaked to the user.

Use generated identifiers for desugaring multiple assignment

---

.github/workflows/kind2-nightly.yml
.github/workflows/kind2-release.yml

It bumps the OCaml version for `kind2-nightly.yml` and `kind2-release.yml`

Bump ocaml version to 4.14.1 in GitHub Actions

---

doc/usr/source/2_input/1_lustre.rst
src/flags.ml
src/flags.mli
src/induction/step.ml
src/kEvent.ml
src/lustre/contractChecker.ml
src/modelElement.ml

It also changes the default value for `--dump_witness` to `false`.

Add options: --print_cex, --print_witness, and --dump_deadlock

---

src/realizability.ml

Kind 2 underreports conflicting constraints since v1.6.0 (036b817). That version started to use the next values for computing the unsat core. Running Kind 2 with Z3 4.12.1 on the Oven example (described in the realizability checking report) triggers the issue.

Fix computation of conflicting constraints: underreporting

---

src/lustre/lustreNodeGen.ml

It impacts on the computation of IVCs and conflicting constraints for system models with contract modes.
Bug introduced in v1.8.0.

Fix classification of contract mode elements in new front-end

---

src/lustre/lustreContext.ml
src/lustre/lustreContract.ml
src/lustre/lustreContract.mli
src/lustre/lustreNode.ml
src/lustre/lustreSlicing.ml

Kind 2 triggered a `Not_found` exception when simulating systems with imported subnodes using the new front-end. When `map_top_reconstruct_and_add` tried to map local variable 'sofar' of an imported subnode without assumptions, the code did not find the variable in the corresponding transition system. This was not an issue in the old front-end because the 'sofar' variable was not being added to locals, and the mapping was not triggered. This commit solves the issue by preventing no-slicing step from removing the 'sofar' variable when the contract has no assumptions.
To reproduce the issue, simulate the following system model with the interpreter for a couple of steps:
```
node imported N(x: int) returns (y:int);
(*@contract
guarantee y>x;
*)
node M(x: int) returns (y:int);
let
y = N(x); …
```

Fix simulation of systems with imported subnodes

---

doc/usr/source/9_other/2_contract_semantics.rst
src/lustre/lustreTransSys.ml

It checks non-vacuity of contract mode implications twice. First, considering only the info of the contract. Then, considering the body of the associated node (if any).

Add additional non-vacuity check for modes

---

doc/usr/source/3_output/3_exit_codes.rst
src/flags.ml
src/flags.mli
src/kind2Flow.ml

This option allows the user to select the exit code convention that Kind 2 should follow:
- results_and_errors = use exit code to report analysis results and errors (default)
- only_errors = only use a non-zero exit code for errors

Add --exit_code_mode option

---

src/smt/MathSATDriver.ml
src/terms/bitvector.ml
src/terms/bitvector.mli

Workaround for a bug in MathSAT:
`(get-value (= x #b0000))` throws "syntax error, unexpected BINCONSTANT"
`(get-value (= x (_ bv0 4)))` works fine

Use bitvector constant extension in MathSAT

---

src/lustre/contractChecker.ml
src/lustre/lustreNode.ml
src/lustre/lustreNode.mli

When printing Lustre constraint representing the set of viable states, it uses a Lustre variable of the original model to refer to a node call output, as opposed to a node call reference, if a Lustre variable is available.

Use Lustre variable for node calls whenever possible

---

src/lustre/lustreTransSys.ml
tests/regression/success/subrange_bug.lus

Fixed a bug with subranges (dealing with int vs enum types, similar to a previous bug fix). For an example of the bug, see the new test file.

Fix bug with subranges

---

src/lustre/lustrePath.ml

Commit 9efb635 does not take into account stateless variables can refer to previous values of stateful variables.
Fixes #1007.

Fix trace reconstruction for stateless variables

---

src/lustre/lustreAstHelpers.ml
src/lustre/lustreAstHelpers.mli
src/lustre/lustreTypeChecker.ml
tests/ounit/lustre/lustreTypeChecker/extensional_array_equality2.lus
tests/ounit/lustre/testLustreFrontend.ml

Detect extensional array equality in complex/nested types

Extensional array equality bug fix

---

src/lustre/lustreArrayDependencies.ml
src/lustre/lustreArrayDependencies.mli
tests/ounit/lustre/testLustreFrontend.ml
tests/regression/success/test_recursive_array_def.lus

Array accesses of the form `A[0]` and `A[n-i]` are allowed if they do not occur (directly or indirectly) in the definition of the array `A` itself.

Lift restriction on array accesses

---

src/lustre/lustreAstInlineConstants.ml
src/lustre/lustreNodeGen.ml
src/lustre/lustreTypeChecker.ml

Commit 5439c29 introduced this transformation (I do not know why), but it was the source of several bugs (see 54ded7a, c2d6105). This commit removes the transformation.

Do not transform enum types to abstract types

---

src/lustre/lustreAstHelpers.ml
src/lustre/lustreAstHelpers.mli
src/lustre/lustreTypeChecker.ml
src/lustre/typeCheckerContext.ml
src/lustre/typeCheckerContext.mli
tests/ounit/lustre/testLustreFrontend.ml

When type checking node calls, consider everything in the same context

Array length constraints, update node call type checking context

---

src/ic3ia/IC3IA.ml
tests/regression/falsifiable/ic3ia_bug.lus

The system definition should only be asserted when solving inductive relative queries. Otherwise, get_bad_cube might incorrectly use assumptions on the state at the beginning of a transition.
Fixes #1036

Fix soundness bug in IC3IA engine

---

src/certif/certifChecker.ml
src/ic3ia/IC3IA.ml
src/ic3ia/IC3IA.mli
src/inputSystem.ml
src/inputSystem.mli
src/kind2Flow.ml
src/lustre/lustreNode.ml
src/lustre/lustreNode.mli
src/lustre/lustreNodeGen.ml
src/lustre/lustreSimplify.ml
src/lustre/lustreSlicing.ml
src/lustre/lustreTransSys.ml
src/lustre/lustreTransSys.mli
src/nativeInput.ml
src/terms/stateVar.ml
src/terms/stateVar.mli
src/transSys.ml
src/transSys.mli

Each IC3IA engine instance applies slicing to the transition system for the property it is checking. This ensures that an engine instance only shuts down if the sliced system contains unsupported features. Previously, all instances would shut down if any property included unsupported features.

Apply slicing in IC3IA engine instances

---

schemas/kind2-output.json
schemas/kind2-output.xsd
src/kEvent.ml
src/property.ml
src/property.mli

Most importantly, all output types (JSON, XML, and terminal) now distinguish between candidate, generated, and candidate generated properties. This allows for accurate fine-grained filtering of properties generated by abstract interpretation.

Give more detailed information about property types in all output formats

---

src/lustre/lustreTypeChecker.ml
tests/regression/success/assumption_on_global_const.lus

See tests/regression/success/assumption_on_global_const.lus as an example that triggers the bug

Fix bug that erroneously disallowed refinement type assumptions from referencing global constants

---

src/lustre/lustreInput.ml

This fixes a bug where generated imported nodes could contain unflattened refinement types (which loses type information when converting to contract elements)

Rearrange pipeline steps to perform ref type flattening after imported node generation

---

src/kEvent.ml
src/transSys.ml
src/transSys.mli

The IC3IA engine slices the transition system based on the property to be checked. This PR filters out notifications for properties that are not in the sliced transition system.

Filter updates on properties that are not in the system

---

src/kEvent.ml
src/transSys.ml

Fixes for commit 1cbc4d1

---

src/flags.ml
src/flags.mli
src/kind2.ml
src/lustre/lspInfo.ml
src/lustre/lspInfo.mli
src/lustre/lustreGenRefTypeImpNodes.ml
src/lustre/lustreInput.ml
src/lustre/lustreInput.mli
src/lustre/lustreTransSys.ml

1. Add flag --lus_main_type which allows the user to specify a main type for realizability checking
2. Augment the LSP info to include whether or not the main type contains some refinement type

Add --lus_main_type flag and give info about type declarations in LSP info

---

src/lustre/lustreInput.ml

Fix bug that was triggered when calling kind 2 with realizability checking enabled but environment checking disabled, e.g. 
`kind2 --enable CONTRACTCK --lus_main N --check_environment false check_env_bug.lus`
with Lustre file 
```
-- check_env_bug.lus
node imported N() returns (y:int);
```

Fix bug when checking realizability but not environment

---

src/lustre/lustreGenRefTypeImpNodes.ml

Stop duplicating type declarations when generating imported nodes.
Note: `LGI.gen_imp_nodes` processes type and constant declarations included in `const_inlined_type_and_consts`, but these declarations should not be included in the result.

Imported node generation bug fix

---

src/lustre/lustreInput.ml
tests/regression/success/flatten_ref_type_in_poly_node.lus

The flattening must be done after instantiating polymorphic nodes.

Reorder flattening of refinement types in pipeline

---

src/lustre/lustreAstNormalizer.ml
src/lustre/typeCheckerContext.ml
src/lustre/typeCheckerContext.mli
tests/regression/success/const_id_arg.lus

Abstract if node argument is enum variant

---

src/certif/certifChecker.ml

Previously, models were retrieved using get-model, which could cause issues when minimizing invariants for Lustre models with arrays encoded as values of an uninterpreted sort, FArray, with arity 2. If the Lustre model includes arrays for two different element types (e.g., FArray Int Bool and FArray Int Int), Z3 returns models where the universes for FArray Int Bool and FArray Int Int may contain constants with the same name (e.g. FArray!val!3).

Use get_var_values to get model in certifChecker

---

doc/usr/source/2_input/1_lustre.rst

The code block at the bottom of the section on [frame conditions](https://kind.cs.uiowa.edu/kind2_user_docs/v2.2.0/2_input/1_lustre.html#frame-conditions) is missing the closing `fi`.

docs: add missing fi in frame code block

---

doc/usr/source/2_input/1_lustre.rst
doc/usr/source/9_other/8_interpreter.rst
src/lustre/lustreInput.mli

The docs make mention of a `--lustre_main` flag which was replaced with `--lus_main` in 467f66ad88d7422bbef8212c6678ec5c4d7df56a

docs: fix references to lustre_main in docs

---

src/lustre/lustreAstNormalizer.ml
tests/regression/success/history1.lus

This issue caused the step counter to not be introduced when the history constructor was used in a contract.

Fixed incorrect variable renaming in bcccc88

---

src/lustre/typeCheckerContext.ml
tests/ounit/lustre/lustreTypeChecker/undeclared_type_06.lus
tests/ounit/lustre/testLustreFrontend.ml

Bug introduced in be290ed. Notice that desugaring of any operators occurs before type checking. Previous code, `SI.add id ty_vars`, does not work because it leads to incorrect positions being reported in error messages.

Fix check of undeclared types in any operators

---

src/doc/copy.sh

`/bin/bash` is not guaranteed to exist on all systems. Replacing the shebang with `#!/usr/bin/env bash` increases portability for these systems.
Quoting arguments in bash prevents weird problems with [word splitting and globbing](https://www.shellcheck.net/wiki/SC2086).

Make `src/docs/copy.sh` a little more robust

---

src/lustre/lustreAstNormalizer.ml
src/lustre/lustreNodeGen.ml
tests/regression/success/subrange_local_free_const.lus

Note that global constants without a definition are currently treated as system parameters.

Fix handling of subrange constraints for free constants

---

src/lustre/lustreAstNormalizer.ml
src/lustre/lustreTypeChecker.ml

The refinement type is desugared later, ensuring that the type information of the bound variable is preserved. This PR also removes the restriction of accepting only quantified bounds with constant type expressions, which is necessary due to the use of the `counter*` variable in the refinement type.

Use a refinement type for the type of history index

---

src/lustre/generatedIdentifiers.ml
src/lustre/generatedIdentifiers.mli
src/lustre/lustreAstHelpers.mli
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreAstNormalizer.mli
src/lustre/lustreInput.ml
src/lustre/lustreNode.ml
src/lustre/lustreNode.mli
src/lustre/lustreNodeGen.ml
src/lustre/lustreSimplify.ml
src/lustre/lustreSlicing.ml
src/lustre/lustreSyntaxChecks.ml
src/lustre/lustreSyntaxChecks.mli
src/lustre/lustreUserFunctions.ml
src/lustre/lustreUserFunctions.mli
src/lustre/typeCheckerContext.ml
src/lustre/typeCheckerContext.mli

Currently, only calls to functions that meet all the following criteria are accepted: they are fully specified, either have no contract or are annotated as transparent, do not include asserts or array definitions, and have only one output.
Requires: #1112 (amended in #1114)

Add support for function calls with arguments containing quantified vars

---

src/terms/term.mli
src/utils/graph.ml
src/utils/graph.mli

While working on other things I stumbled on typos and minor mistakes in the developer facing documentation:
1. The graph data structure claims to only represent acyclic graphs but it has no problems with cycles.
2. The graph data structure claims that it only works with maps which aren't surjective to preserve the graph structure. What it actually requires is an injective map.
3. Minor typos here and there.

Minor developer documentation cleanups

---

tests/run.sh

1. Use `/usr/bin/env bash` instead of `/bin/bash` as `/bin/bash` is not guaranteed to exist
2. Use `$(...)` not `` `...` `` for command substitution. `` `...` `` is old and has lots of undefined behavior.
3. Move print error to the top. In bash functions must be defined before they are called. `print_error`
was defined after its call site resulting in an error when called.
4. `$@` is [ambiguous](https://www.shellcheck.net/wiki/SC2124), `$*` explicitly produces the behavior we are relying on.

Make test runner script a little more resiliant

---

.github/actions/build-kind2/action.yml
src/lustre/lustreUserFunctions.ml
src/lustre/typeCheckerContext.ml
src/lustre/typeCheckerContext.mli

A function that can be abstracted because it has a contract with guarantees or modes, or outputs with refinement types or subrange types, must be marked as transparent to allow it to be inlined.

Update the set of inlinable functions

---

src/lustre/lustreSyntaxChecks.ml
src/lustre/lustreSyntaxChecks.mli
tests/ounit/lustre/lustreSyntaxChecks/history_quantified_var_1.lus
tests/ounit/lustre/lustreSyntaxChecks/history_quantified_var_2.lus
tests/ounit/lustre/lustreSyntaxChecks/history_quantified_var_3.lus
tests/ounit/lustre/testLustreFrontend.ml

For examples, see the new test cases

Disallow quantified variables in history type constructor

---

src/lustre/lustreDesugarFrameBlocks.ml
src/lustre/lustreTypeChecker.ml
src/lustre/lustreTypeChecker.mli
tests/ounit/lustre/lustreTypeChecker/array_frame.lus
tests/ounit/lustre/testLustreFrontend.ml
tests/regression/falsifiable/array_frame.lus

This PR accomplishes two tasks.
1. Address the bug in the following example, where frame blocks and arrays with mixed indexed/nonindexed definitions did not work properly (see changes to `lustreDesugarFrameBlocks.ml`
```
node N() returns (A: int^N);
let
frame (A)
A = 0^N;
--A[i] = 0;
let
A[i] = pre A[i] + 1;
tel
check true -> A[0]=1;
tel
```
2. Restrict the definitions of multi-dimensional arrays such that if indices are used, there must be an index for each dimension. For example, if ```B: int^4^4```, it can be defined with ```B = <expr>``` or ```B[i][j] = <expr>```, but not with ```B[i] = <expr>```. (see changes to `lustreTypeChecker.ml`

Array frame fix

---

src/lustre/lustreAstNormalizer.ml
tests/regression/success/multi_indices_array.lus

The test case (included below) used to throw an exception due to two bugs in normalization. In the first place, the generated `nexpr` threw away all indices except for the first index. In the second place, if there was a normalized expression under a `pre` with indices, only one of those indices was pushed "outside" the pre, (potentially) creating malformed expressions.
Note--I don't fully understand why the second change is necessary; maybe we should discuss this before merging.
```
node N() returns (out: int^4^4);
let
out[i][j] = 0 -> pre (out[i][j] + 1);
check out[0][0] = 0 -> true;
tel
```

Fix bug with normalization of multidimensional arrays

---

src/lustre/generatedIdentifiers.ml
src/lustre/generatedIdentifiers.mli
src/lustre/lustreAstNormalizer.ml
src/lustre/lustreDesugarFrameBlocks.ml
src/lustre/lustreErrors.ml
src/lustre/lustreErrors.mli
src/lustre/lustreGenRefTypeImpNodes.ml
src/lustre/lustreGenRefTypeImpNodes.mli
src/lustre/lustreInput.ml
src/lustre/lustreInput.mli
src/lustre/lustreNodeGen.ml
src/lustre/lustreRemoveMultAssign.ml
src/lustre/lustreRemoveMultAssign.mli
src/lustre/lustreTypeChecker.mli
src/utils/lib.ml
src/utils/lib.mli

Fixes kind2-mc/kind2-dev#150
Also see below for a more in depth test case, which correctly report N's environment as unrealizable because initially, it is not possible for x+2 to be less than 0 and x + (3+l) (which is  x + (3+0) = x+3) to be greater than 0.
However, N2's environment is correctly reported as realizable.
```
contract S1(x, y: int) returns (z: bool);
let
assume x < 0 and 0 < y;
tel
node M (x: int) returns (y: int)
let
y = x;
tel
node imported N(x:int) returns (y: bool; y2: int);
(*@contract
var l: int = 0 -> pre (M(4 + 2));
var m: int = 3;
import S1(x+2, x+ (3 + l)) returns (y);
guarantee y2 + l > 0;
*)
node imported N2(x:int) returns (y: bool; y2: int);
(*@contract
var m: int = 1;
var l: int = 2 + m;
import S1(x+0, x+ (1 + l)) returns (y);
guarantee y2 + l > 0;
*)
``` …

Env realizability imports fix

---

src/lustre/lustreAstNormalizer.ml
src/lustre/lustreInput.ml
src/lustre/lustreInstantiatePolyNodes.ml
src/lustre/lustreInstantiatePolyNodes.mli
tests/regression/falsifiable/polymorphic_gids.lus

At the `lustreInstantiatePolyNodes.ml` step, we create a monomorphization for each concrete instance of each polymorphic node (e.g., instantiating `M<<T>>` with `M<<int>>` and `M<<bool>>`). We need to do the same thing in the generated identifiers data structure, that is, create generated identifiers for each monomorphization.
Most of the diff in this PR is just for passing `gids` throughout the module; the substantive changes are in the `gen_poly_decl` function

Monomorphize gids

---

src/lustre/lustreGenRefTypeImpNodes.ml

Fix a name clash bug with type realizability checking. Example test case previously failing with `--enable CONTRACTCK`
```
type HostId = subtype { i: int | i < 10 };
type VoteMsg = struct {
sender: HostId;
vote: int;
};
type MsgVariant = enum {VoteReqMsg, VoteMsg};
```

Fix name clash bug
