src/lustreSimplify.ml, tests/lustre/test-issue-236.lus
=> Don't fail if property is an input

src/PDR.ml, src/analysis.ml, src/base.ml, src/kind2.ml, src/lib.ml, src/lib.mli, src/step.ml, src/termLib.ml, src/termLib.mli, src/transSys.ml, src/transSys.mli, tests/lustre/contracts/PilotFlying-condacts-QSV5.lus
* added  some minisleep at the end of an analysis to wait for incoming messages
* fixed sigalrm handling
* make sure all messages from previous analysis are popped
* reverted local variables in pilot flying
=> Improved stability, fixed refinement related bugs.

src/kind2-terms.mltop, src/ltree.ml
=> Bind multiple vars in one lambda simultaneously

src/analysis.ml, src/event.ml, src/event.mli, src/kind2.ml, src/lib.ml, src/transSys.ml, src/transSys.mli
```
kind2 -xml --modular false --compositional false test/lustre/contracts/simple-ok-call.lus
```
```xml
<?xml version="1.0"?>
<Results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Log class="info" source="parser">kind2 v0.1.1-1091-g138d6d8</Log>
<Analysis>
<Compositional>false</Compositional>
<Modular>false</Modular>
<System>top</System>
</Analysis>
<Property name="sub[l26c8].__abs_2" lifted="true" generated="false">
<Position><File></File><Row>12</Row><Col>4</Col></Position>
<Runtime unit="sec" timeout="false">0.156</Runtime>
<Answer source="indstep">valid</Answer>
</Property>
<Contract name="contract_top" global="false">
<Position><File></File><Row>22</Row><Col>2</Col></Position>
<Runtime unit="sec" timeout="false">0.156</Runtime>
<Answer source="indstep">valid</Answer> …
```
=> XML output for modular / compositional

tests/lustre/contracts/PilotFlying-top.lus
Top level contract encoded as an assume / guarantee contract in a property.
=> Pilot flying, contract as property, top only

src/flags.ml.in, src/flags.mli, src/refiner.ml
=> Added flag activating refinement

pullrequest_server/gendoc, pullrequest_server/pullrequest_server.eliom
For now, this is put on http://kind.cs.uiowa.edu/kind2_dev_doc
=> Generate documentation on pull request merge

src/SMTLIBSolver.ml
=> Kill solver instance if not responding on timeout

src/event.ml, src/event.mli, src/flags.ml.in, src/flags.mli, src/step.ml, tests/lustre/ind_print_cex.lus
* plain text and xml
* relevant flag (default false)
* no overhead if inactive
File `tests/lustre/ind_print_cex.lus`
```
node bla(in: real) returns (out: real) ;
var tmp: real ;
let
tmp = in -> pre in ;
out = in -> pre tmp ;
--%PROPERTY out = (in -> pre (in -> pre in )) ;
tel
```
**Make sure you only activate BMC and IND otherwise there may be not step cex, e.g. IC3 proves.**
Plain text:
```
> kind2 --enable BMC --enable IND --ind_print_cex true tests/lustre/ind_print_cex.lus
```
```
<Warning> Property (out = (in -> (pre (in -> (pre in))))) has a step k-induction counterexample for k=2 after 0.034s.
Counterexample:
Node bla ()
== Inputs ==
in  2 0
== Outputs ==
out 0 0
== Locals ==
tmp 0 2
<Success> Property (out = (in -> (pre (in -> (pre in))))) is valid by inductive step after 0.078s. …
```
=> Step counterexample printing

src/kind2.ml, src/lustrePath.ml, src/yicesDriver.ml
Bug fix for xml output.
Bug fix for incorrect model reconstruction of eliminated variables.
Xor support for Yices 1.
=> Various bug fixes

src/flags.ml.in, src/flags.mli, src/testgenDF.ml, src/testgenIO.ml
* graph only option (do not log testcases) `--testgen_graph_only <bool>` (default false)
* better looking graph
* restart after 250 actlits have been used (100 previously)
=> Testgen improvements

src/event.ml, src/flags.ml.in, src/kind2.ml, src/lib.ml, src/lib.mli, src/step2.ml, src/step2.mli
Added a new process performing 2-induction and nothing else.
* splits the properties between falsifiable and unfalsifiable,
* broadcasts as invariant whatever it can (if properties are 1-true or more),
* waits for a new message to come in and loops.
On by default.
=> 2-induction

Makefile.in, doc/usr/Makefile, doc/usr/content/1_techniques/1_techniques.md, doc/usr/content/2_input/2_arrays.md, doc/usr/content/9_other/2_contract_semantics.md, doc/usr/rsc/github-pandoc.css.include, doc/usr/rsc/options, doc/usr/rsc/template.latex
- Generation of html documentation (self-contained) with pandoc.
- compile / preprocess files only if changes.
- Support utf8 in pdf output.
- Some fixes in links of user documentation.
=> Generation of html user documentation

lfsc/checker/check.cpp, lfsc/checker/check.h, lfsc/signatures/kind.plf, lfsc/signatures/th_int.plf, lfsc/signatures/th_real.plf, src/certifChecker.ml, src/jkindParser.ml, src/proof.ml, src/proof.mli
- Some preliminary support for integer and real LFSC proof
- Documentation
- support for _identifiers in LFSC checker
=> Merge with fork of certificates

examples/two_counters.lus, pullrequest_server/test_pr, src/analysis.ml, src/debug.ml, src/doc/doc_intro.txt, src/event.ml, src/flags.ml, src/flags.mli, src/invarManager.ml, src/kind2.odocl, src/lib.ml, src/lib.mli, src/lustre/lustreAst.ml, src/lustre/lustreContext.ml, src/lustre/lustreLexer.mll, src/lustre/lustrePath.ml, src/pretty.ml, src/pretty.mli, src/scope.ml
Show colors in textual ouptut. A new flag `--color` controls this behavior and set to `true` by default.
%notest
=> Colorized output

src/doc/doc_intro.txt, src/doc/include/style.css, src/myocamlbuild.ml.in, src/pretty.mli
Cleaner developer's documentation (see http://kind.cs.uiowa.edu/kind2_dev_doc/).
%notest
=> Prettier documentation

src/lustre/lustreDeclarations.ml, src/lustre/lustreNode.mli, src/lustre/lustrePath.ml, src/model.ml
**Only for plain text**, will not show up in XML
=> Mode info in cex

src/certifChecker.ml, src/flags.ml, src/kind2.ml, src/proof.ml, src/proof.mli, src/stat.ml, src/stat.mli, src/termLib.ml
Better error messages and CVC4 handling for proofs
=> Certificates

tests/run.sh
=> fix make test

CHANGES.md, doc/usr/content/9_other/3_test_generation.md, doc/usr/content/9_other/5_proofs.md, doc/usr/content/9_other/6_contract_generation.md, doc/usr/rsc/template.latex, doc/usr/src/preprocess.ml, src/debug.mli, src/kind2.odocl
- fixed usr and dev documentation
- added contract generation to changelog and user doc
=> Docs and changelog fixes / updates

CHANGES.md, Makefile.in, configure.ac, doc/usr/content/2_input/2_arrays.md, src/analysis.ml, src/flags.ml, src/lustre/lustrePath.ml
=> Last minute changes

src/analysis.ml, src/flags.ml, src/flags.mli, src/invarManager.ml, src/stat.ml
* per-analysis timeout: `--timeout_analysis`
* colors in final result pretty printing were messy, tuned it a bit
=> per-analysis timeout + fixed result pprinting a bit

pullrequest_server/scripts/qsub-benchmark
=> missing test script

.travis.yml, README.md, src/interpreter.ml, src/kind2Flow.ml
- don't slice transition system when interpreting
- fail if trace for constant input is inconsistent
- travis build status in readme
=> Bug fixes in interpreter and travis status

pullrequest_server/pullrequest_server.eliom
This is still hard coded but changing it is easier.
=> Top-level configuration for pull request hook

src/lustre/lustreDeclarations.ml
This closes kind2-mc/kind2#472
=> Improved error messages in contract parsing

src/simplify.ml
=> Added missing cases in simplification of to-real and to-int

README.rst, doc/usr/source/2_input/3_machine_ints.rst, doc/usr/source/index.rst
The section is added under "Inputs and Outputs" under "Lustre Input". If anything needs to be changed let me know @arjunvish @daniel-larraz
=> Add machine ints section to manual

doc/usr/source/2_input/3_machine_ints.rst, src/transSys.ml
Added an error message to Kind2 when Yices(2) solver is used along with BV logic.
=> Final commit for machine integers with Kind2.

src/ic3/IC3.ml
When transition relation comes from a contract it may be unsatisfiable.
=> Fix in IC3: transition relation is asserted after zero cex check

src/certif/certifChecker.ml, src/smt/SMTSolver.ml, src/smt/SMTSolver.mli
CertifChecker.minimize_invariant was failing when Flags.Smt.check_sat_assume is false
=> Temporary fix for an issue in the certif checker

.gitignore, src/certif/proof.ml, src/dead_code/hset.ml, src/inputParser.ml, src/lustre/lustreIdent.ml, src/lustre/lustreIndex.ml, src/model.ml, src/terms/decimal.ml, src/terms/ltree.ml, src/terms/termLib.ml, src/utils/hashconsStrong.ml, src/utils/hashconsWeak.ml, src/utils/lib.ml, src/utils/pretty.ml
- `make test`-ed with ocaml 4.07 and 4.09
- `Pervasives` -> `Stdlib` 
- Travis CI may need changes as we now depend on a new library.(Edit: updated now)
=> Catchup with ocaml 4.09

src/lustre/lustreExpr.ml
=> Fix uminus type for subranges

src/analysis.ml, src/analysis.mli, src/inputSystem.ml, src/inputSystem.mli, src/kind2Flow.ml, src/strategy.ml, src/strategy.mli
See further information in description of proposed pull request #684.
=> Fix returned exit code for modular analysis

src/induction/base.ml
This change shorten the runtime for the following example (using Boolector 3.2.1 master-6fce0a):
```
node count2(turn :bool) returns (bad : bool);
var a :uint8;
var b :uint8;
let 
-- Increment a if Turn is True
a = if turn then (uint8 0) -> pre(a) + (uint8 3) else (uint8 0) -> pre a;
b = if not turn then (uint8 0) -> pre(b) + (uint8 3) else (uint8 0) -> pre b;
bad =  (a = (uint8 2) and b = (uint8 2)) ; 
--%PROPERTY not bad;
tel
```
And it doesn’t seem to harm the performance over the kind2 benchmarks.
=> Reduce number of activation literals in BMC encoding

src/lustre/lustreAst.ml, src/lustre/lustreAstDependencies.ml, src/lustre/lustreAstHelpers.ml, src/lustre/lustreAstHelpers.mli, src/lustre/lustreParser.mly, src/lustre/lustreTypeChecker.ml, tests/lustre/typechecking/shouldFail/test_automaton.lus, tests/lustre/typechecking/shouldFail/test_automaton_ab.lus, tests/lustre/typechecking/shouldFail/test_automaton_circular.lus, tests/lustre/typechecking/shouldFail/test_automaton_hierarchy.lus, tests/lustre/typechecking/shouldFail/test_automaton_state.lus, tests/lustre/typechecking/shouldPass/test_automaton.lus
- Type checking automaton 
- Dependency analysis on automaton states
=> Type check automaton

src/debug.ml, src/debug.mli, src/doc/index.mld, src/flags.ml, src/flags.mli, src/inputSystem.ml, src/inputSystem.mli, src/kEvent.ml, src/kEvent.mli, src/kind2Flow.ml, src/lustre/contractChecker.ml, src/lustre/contractChecker.mli, src/lustre/lustreSlicing.ml, src/lustre/lustreSlicing.mli, src/lustre/lustreTransSys.ml, src/modelElement.ml, src/qe/QE.ml, src/qe/QE.mli, src/smt/SMTSolver.ml, src/smt/SMTSolver.mli, src/utils/lib.ml, src/utils/lib.mli
The current analysis only checks whether the contract of an imported node is realizable or not.
=> New option for checking contracts 

src/ic3/IC3.ml, src/transSys.ml
It also fixes an error message.
=> Fix: take global consts into account in logic detection

src/ic3/IC3.ml, src/qe/QE.ml, src/qe/QE.mli
=> Improve error handling in presence of quantifiers

src/certif/certifChecker.ml, src/kEvent.ml, src/lustre/lustreContext.ml, src/lustre/lustreContext.mli, src/lustre/lustreContract.ml, src/lustre/lustreDeclarations.ml, src/lustre/lustreNode.ml, src/lustre/lustreNode.mli, src/lustre/lustreTransSys.ml, src/nativeInput.ml, src/property.ml, src/property.mli, tests/regression/error/import_type_mismatch.lus, tests/regression/falsifiable/test-issue-707-2.lus, tests/regression/falsifiable/test-issue-721.lus, tests/regression/success/test-issue-707-1.lus
Resolve #701, fix #721, and close #707 too.
=> Fix and update bound checking mechanism for subrange types

src/ivcMcs.ml, src/lustre/contractsToProps.ml, src/lustre/lustreAst.ml, src/lustre/lustreAst.mli, src/lustre/lustreAstDependencies.ml, src/lustre/lustreAstInlineConstants.ml, src/lustre/lustreDeclarations.ml, src/lustre/lustreDependencies.ml, src/lustre/lustreParser.mly, src/lustre/lustreTypeChecker.ml, tests/ounit/lustre/testAstDependencies.ml
=> Add span info to decls

src/certif/certifChecker.ml, src/induction/step.ml, src/induction/step2.ml, src/ivcMcs.ml, src/kEvent.ml, src/kEvent.mli, src/lustre/lustreNode.ml, src/lustre/lustrePath.ml, src/lustre/lustreTransSys.ml, src/nativeInput.ml, src/property.ml, src/property.mli, src/transSys.ml, src/transSys.mli, src/utils/lib.ml, src/utils/lib.mli
=> Declare SoFar(A) invariant when A=A_1..A_n has been proven invariant

src/analysis.ml, src/analysis.mli, src/flags.ml, src/flags.mli, src/inputSystem.ml, src/inputSystem.mli, src/kind2Flow.ml, src/lustre/assumption.ml, src/lustre/assumption.mli, src/lustre/contractChecker.ml, src/lustre/lustreNode.ml, src/lustre/lustreNode.mli, src/postAnalysis.ml, src/qe/abduction.ml, src/qe/abduction.mli, src/realizability.ml, src/realizability.mli, src/simplify.ml, src/simplify.mli
Add option to generate automatically assumptions that blocks the violation of falsified properties
=> Assumption Generation

src/inputSystem.ml, src/inputSystem.mli, src/ivcMcs.ml, src/ivcMcs.mli, src/lustre/lustreContractGen.ml, src/lustre/lustreInput.ml, src/lustre/lustreInput.mli, src/lustre/lustreNode.ml, src/lustre/lustreNode.mli, src/lustre/lustrePath.ml, src/lustre/lustrePath.mli, src/lustre/lustreSlicing.ml, src/lustre/lustreTransSys.ml, src/lustre/lustreTransSys.mli, src/postAnalysis.ml, src/strategy.ml, src/strategy.mli, src/subSystem.ml, src/subSystem.mli, src/utils/lib.ml, src/utils/lib.mli
This PR adds the functionality required by the use-case described in #752, and extends it to the rest of functions provided by Kind 2.
=> Add support for Lustre models with multiple MAIN annotations

src/lustre/lustrePath.ml
PR #728 is incomplete: it only prints values of ghost variables in plain text output. This PR extends it to print them in JSON and XML output too.
=> Print values of ghost variables in counterexamples (JSON/XML output)

src/inputSystem.ml, src/lustre/lustrePath.ml, src/lustre/lustrePath.mli
This is specially useful for examining the values assigned to free constants.
=> Print values of constants in counterexamples

schemas/kind2-output.json, schemas/kind2-output.xsd, src/inputSystem.ml, src/inputSystem.mli, src/ivcMcs.ml, src/kEvent.ml, src/kEvent.mli, src/kind2Flow.ml, src/log.ml, src/lustre/assumption.ml, src/lustre/contractChecker.ml, src/lustre/contractChecker.mli, src/lustre/lustreSlicing.ml, src/modelElement.ml, src/modelElement.mli, src/realizability.ml, src/realizability.mli
When a contract is proven unrealizable, it shows one concrete deadlocking trace and an unrealizable core for it.
=> Show deadlocking trace and unrealizable core

src/modelElement.ml
This PR identifies the individual contribution of require and ensure clauses.
=> Include require and ensure clauses in cores

src/lustre/lustreAstDependencies.ml, src/lustre/lustreAstInlineConstants.ml, src/lustre/lustreInput.ml, src/lustre/lustreNodeGen.ml, src/lustre/lustreSyntaxChecks.ml, src/lustre/lustreSyntaxChecks.mli, src/lustre/typeCheckerContext.ml, src/lustre/typeCheckerContext.mli
- Add check for locals having a definition
- Fix a dependency issue (inner node calls in condact statements being ignored)
- Flatten equations that have nested list expression on the right hand side
=> Fix misc errors

src/lustre/lustreAstInlineConstants.ml, src/lustre/lustreNodeGen.ml, src/lustre/lustreSyntaxChecks.ml, tests/lustre/typechecking/shouldFail/test_condact.lus
Various syntax checks and bug fixes
=> Syntax checks

src/invgen/invGenMiner.ml
It also removes warning 27 instances from invGenMiner module
=> Fix and tweak octagons_3 function in invGenMiner

src/lustre/lustreAstNormalizer.ml, src/lustre/lustreAstNormalizer.mli, src/lustre/lustreNodeGen.ml, src/lustre/lustreSyntaxChecks.ml, src/lustre/lustreTypeChecker.ml, tests/experimental/error/test_node_call_with_inductive_array_index.lus, tests/param/bus.lus
Also, couple of other minor changes and fixes. A large amount of lines of this PR are just fixing tabbing from 3 spaces to 2 spaces
=> Add error checks for symbolic array indices and quantified variables in node calls

Makefile, src/flags.ml, src/flags.mli, src/kind2.ml, src/lustre/lustreInput.ml
add old_frontend flag
remove only_tc and no_tc flags
change only_parse to behave like only_tc when old_frontend is false
make sure that when only_parse is true a main node is not needed
=> Alter flags for typechecking

src/inputSystem.ml, src/inputSystem.mli, src/kind2.ml, src/lustre/lustreInput.ml, src/lustre/lustreInput.mli
Reapply fix #695 after introducing new front-end.
=> Unify only_parse exit points for old and new frontend

src/invgen/invGenMiner.ml
Prevent invariant generators from terminating early due to assertion failure.
Related models: tests/param/test/{bus.lus,shared_buffer.lus}
=> Disable mining of invariants in quantified terms

src/lustre/lustreSyntaxChecks.ml, tests/experimental/success/array_ext_eq.lus
Also add a test for extensional array equality
=> Clocked inputs and outputs currently not supported

src/induction/step.ml
Before this PR, the inductive step check could incorrectly declare a property k-inductive in some cases after a contract has been refined in compositional verification.
=> Make sure all properties have been confirmed by base in step check

src/flags.ml
Use cvc5 as QE solver if cvc5 is selected as main solver and no QE solver is provided
=> Tweak QE solver selection

src/smt/Yices2SMT2Driver.ml, src/smt/Z3Driver.ml, src/terms/termLib.ml
This partially reverts commit 2b3e774. It fixes the issue that commit 2b3e774 addressed without breaking the logic setting for Yices 2.
=> Fix SMT-LIB logic setting for Yices 2 (QF_*LIRA)

src/smt/SMTSolver.ml
In this way no pre-/post-processing is required.
=> Send a get-value query for each term

doc/usr/source/1_techniques/4_ic3.rst, src/flags.ml, src/flags.mli, src/invarManager.ml, src/invarManager.mli, src/kind2Flow.ml, src/processCall.ml, src/processCall.mli
It also also add an option (`--ic3ia_max <int>`) to set the limit.
=> Limit maximum number of IC3IA parallel processes

src/lustre/lustreSyntaxChecks.ml, src/lustre/lustreSyntaxChecks.mli
Fix bug of bad error message when assert is placed in frame block init eqs
=> Fix assert in frame block init bug

src/lustre/lustreTransSys.ml, tests/regression/success/test-issue-1023.lus
Bug introduced in 8d9825b. Fix issue #1023.
=> Fix node calls with const param that are nested inside other nodes

src/messaging.ml
It avoids use of Thread.exit which now raises Thread.Exit exception
=> Fix issue with OCaml 5.0.0+

src/lustre/lustreAstNormalizer.ml
If the types of the inputs and outputs of a node/contract are equal to the types of the inputs and outputs of an imported contract, do not add the constraints (assumptions and guarantees) associated to the latter. Future optimization: use subtyping relation instead of equality.
=> Do not add (some) redundant subrange constraints

src/transSys.ml, tests/regression/success/issue_1043.lus
=> Add logics from free constant types and constraints

.github/workflows/kind2-ci.yml
It fixes a ZeroMQ compilation issue in CI.
=> Use ubuntu-latest in CI

src/lustre/lustreTypeChecker.ml
This reintroduces a restriction lifted in PR #1112 until we have time to address it properly. The restriction was initially lifted to allow an existentially quantified index for a history variable to have a refinement type defining its range between zero and the current time. This PR applies a workaround to permit only that specific case.
=> Reject quantified bounds with non-constant refinement types

src/lustre/lustreGenRefTypeImpNodes.ml
=> Keep ghost vars when checking realizability of a node's environment

src/analysis.ml, src/analysis.mli, src/kEvent.ml, src/lustre/contractChecker.ml, src/lustre/lustreContract.ml, src/lustre/lustreGenRefTypeImpNodes.ml, src/lustre/lustreGenRefTypeImpNodes.mli, src/lustre/lustrePath.ml, src/lustre/lustrePath.mli, src/lustre/lustreTransSys.ml, src/modelElement.ml
Bandaid solution to leaking generated node names; a more robust solution will come in a future PR.
Note to Daniel- after #1127 is merged, I will double check this PR. Once I double check, I will post another comment when I think it is ready to merge.
=> Fix .poly_N tag leak in property names
